# Generated by Django 3.2.18 on 2023-05-05 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 1, 17, 3, 542272, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PromptCheckpointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_message', models.TextField(verbose_name='Prompt Message')),
                ('version', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(related_name='prompts', to='minestructure.PromptTagModel')),
            ],
            options={
                'verbose_name': 'Prompt Checkpoint',
                'verbose_name_plural': 'Prompt Checkpoints',
            },
        ),
    ]
