# Generated by Django 3.2.18 on 2023-05-05 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0002_auto_20230505_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptcheckpointmodel',
            name='message_prefix',
            field=models.TextField(default='', verbose_name='Message Prefix'),
        ),
        migrations.AddField(
            model_name='promptcheckpointmodel',
            name='message_suffix',
            field=models.TextField(default='', verbose_name='Message Suffix'),
        ),
        migrations.AddField(
            model_name='promptcheckpointmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 2, 52, 4, 590225, tzinfo=utc)),
        ),
    ]
