# Generated by Django 3.2.18 on 2023-05-09 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0005_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationcheckpointmodel',
            name='human_blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_role_checkpoints', to='minestructure.blueprintmodel'),
        ),
        migrations.AddField(
            model_name='collaborationcheckpointmodel',
            name='machine_blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_role_checkpoints', to='minestructure.blueprintmodel'),
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 22, 16, 774705, tzinfo=utc)),
        ),
    ]
