# Generated by Django 3.2.18 on 2023-05-09 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0006_auto_20230509_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationcheckpointmodel',
            name='human_blueprint',
        ),
        migrations.RemoveField(
            model_name='collaborationcheckpointmodel',
            name='machine_blueprint',
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 20, 25, 30, 324361, tzinfo=utc)),
        ),
    ]
