# Generated by Django 3.2.18 on 2023-06-16 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0008_auto_20230609_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationsessionmodel',
            name='prompt_checkpoint',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='minestructure.promptcheckpointmodel'),
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 13, 19, 44, 747767, tzinfo=utc)),
        ),
    ]
