# Generated by Django 3.2.18 on 2023-06-22 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0012_auto_20230622_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 16, 29, 52, 455218, tzinfo=utc)),
        ),
    ]
