# Generated by Django 3.2.18 on 2023-06-29 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0013_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 15, 12, 48, 160485, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CollaborationExperimentFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('participant_code', models.CharField(blank=True, max_length=100)),
                ('spec', models.JSONField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='minestructure.collaborationrecordmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='minestructure.collaborationsessionmodel')),
            ],
        ),
    ]
