# Generated by Django 3.2.18 on 2023-06-29 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0014_auto_20230629_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrecordmodel',
            name='owner',
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 18, 19, 37, 247767, tzinfo=utc)),
        ),
    ]
