# Generated by Django 3.2.18 on 2023-06-30 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import minestructure.models


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0015_auto_20230629_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationexperimentfeedbackmodel',
            name='complete_code',
            field=models.CharField(default=minestructure.models.generate_two_digit_identifier, max_length=2),
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 11, 1, 25, 859903, tzinfo=utc)),
        ),
    ]
