# Generated by Django 3.2.18 on 2023-09-05 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0016_auto_20230630_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 5, 34, 3, 438231, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TaskPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('completed_count', models.JSONField(default=dict)),
                ('experiments', models.ManyToManyField(to='minestructure.CollaborationExperimentModel')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('collaboration_records', models.ManyToManyField(related_name='tasks', to='minestructure.CollaborationRecordModel')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minestructure.collaborationexperimentmodel')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minestructure.participantmodel')),
            ],
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='task_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minestructure.taskpool'),
        ),
    ]
