# Generated by Django 3.2.18 on 2023-09-05 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0017_auto_20230905_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 6, 52, 7, 870866, tzinfo=utc)),
        ),
    ]
