# Generated by Django 3.2.18 on 2023-09-16 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0039_auto_20230916_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 22, 10, 36, 808850, tzinfo=utc)),
        ),
    ]
