# Generated by Django 3.2.18 on 2023-09-17 00:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0043_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 0, 6, 53, 549371, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ParticipantTaskFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('collaboration_experiment_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_task_feedbacks', to='minestructure.collaborationexperimentfeedbackmodel')),
                ('ptask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_task_feedbacks', to='minestructure.participanttaskmodel')),
            ],
        ),
    ]
