# Generated by Django 3.2.18 on 2023-09-17 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0053_auto_20230917_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 5, 25, 54, 631634, tzinfo=utc)),
        ),
    ]
