# Generated by Django 3.2.18 on 2023-09-20 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0068_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationexperimentmodel',
            name='promptCheckpoint',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='minestructure.promptcheckpointmodel'),
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 19, 35, 34, 183261, tzinfo=utc)),
        ),
    ]
