# Generated by Django 3.2.18 on 2023-09-20 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0071_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationexperimentmodel',
            old_name='promptCheckpoint',
            new_name='prompt_checkpoint',
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 19, 44, 27, 381080, tzinfo=utc)),
        ),
    ]
