# Generated by Django 3.2.18 on 2023-09-20 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0074_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationexperimentmodel',
            name='backend_version',
            field=models.CharField(default='gpt-4', max_length=100),
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 22, 53, 34, 895594, tzinfo=utc)),
        ),
    ]
