# Generated by Django 3.2.18 on 2023-09-25 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minestructure', '0081_alter_blueprintsharelinkmodel_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBatchFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_version', models.CharField(default='gpt-4', max_length=100)),
                ('spec', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blueprintsharelinkmodel',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 3, 48, 53, 996154, tzinfo=utc)),
        ),
    ]
